# This is a basic workflow to help you get started with Actions

name: EB deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - github

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: nodejs build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - 12.x
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install
      run: npm install

    - name: test
      run: npm test

    - name: package
      run: zip apiacicddj.zip -r ./ -x "*node_modules*" -x "*.git*"
      
    - name: deploy
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: apiacicddj
        environment_name: Apiacicddj-env
        version_label: ${{ github.run_id }}
        region: us-east-1
        deployment_package: apiacicddj.zip
